services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
      - HOST=0.0.0.0
